// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=ts"
// @generated from file github/v1/codex_task.proto (package github.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum github.v1.CodexTaskStage
 */
export enum CodexTaskStage {
  /**
   * @generated from enum value: CODEX_TASK_STAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CODEX_TASK_STAGE_PLANNING = 1;
   */
  PLANNING = 1,

  /**
   * @generated from enum value: CODEX_TASK_STAGE_IMPLEMENTATION = 2;
   */
  IMPLEMENTATION = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(CodexTaskStage)
proto3.util.setEnumType(CodexTaskStage, "github.v1.CodexTaskStage", [
  { no: 0, name: "CODEX_TASK_STAGE_UNSPECIFIED" },
  { no: 1, name: "CODEX_TASK_STAGE_PLANNING" },
  { no: 2, name: "CODEX_TASK_STAGE_IMPLEMENTATION" },
]);

/**
 * @generated from message github.v1.CodexTask
 */
export class CodexTask extends Message<CodexTask> {
  /**
   * @generated from field: github.v1.CodexTaskStage stage = 1;
   */
  stage = CodexTaskStage.UNSPECIFIED;

  /**
   * @generated from field: string prompt = 2;
   */
  prompt = "";

  /**
   * @generated from field: string repository = 3;
   */
  repository = "";

  /**
   * @generated from field: string base = 4;
   */
  base = "";

  /**
   * @generated from field: string head = 5;
   */
  head = "";

  /**
   * @generated from field: int64 issue_number = 6;
   */
  issueNumber = protoInt64.zero;

  /**
   * @generated from field: string issue_url = 7;
   */
  issueUrl = "";

  /**
   * @generated from field: string issue_title = 8;
   */
  issueTitle = "";

  /**
   * @generated from field: string issue_body = 9;
   */
  issueBody = "";

  /**
   * @generated from field: string sender = 10;
   */
  sender = "";

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 11;
   */
  issuedAt?: Timestamp;

  /**
   * @generated from field: optional int64 plan_comment_id = 12;
   */
  planCommentId?: bigint;

  /**
   * @generated from field: optional string plan_comment_url = 13;
   */
  planCommentUrl?: string;

  /**
   * @generated from field: optional string plan_comment_body = 14;
   */
  planCommentBody?: string;

  /**
   * @generated from field: string delivery_id = 15;
   */
  deliveryId = "";

  constructor(data?: PartialMessage<CodexTask>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "github.v1.CodexTask";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stage", kind: "enum", T: proto3.getEnumType(CodexTaskStage) },
    { no: 2, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "repository", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "base", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "head", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "issue_number", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "issue_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "issue_title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "issue_body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "issued_at", kind: "message", T: Timestamp },
    { no: 12, name: "plan_comment_id", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 13, name: "plan_comment_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 14, name: "plan_comment_body", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 15, name: "delivery_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CodexTask {
    return new CodexTask().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CodexTask {
    return new CodexTask().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CodexTask {
    return new CodexTask().fromJsonString(jsonString, options);
  }

  static equals(a: CodexTask | PlainMessage<CodexTask> | undefined, b: CodexTask | PlainMessage<CodexTask> | undefined): boolean {
    return proto3.util.equals(CodexTask, a, b);
  }
}

