{
 "title": "Argo Workflows Metrics - (v3.6 and above)",
 "description": "Metrics from Argo Workflows compatible with multi-Prometheus origins like Thanos.",
 "tags": [ "argo" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "Kubernetes Cluster",
    "query": {
     "query": "label_values(argo_workflows_total_count,prometheus)"
    }
   },
   {
    "name": "ns",
    "label": "WF Controller Namespace",
    "query": {
     "query": "label_values(argo_workflows_total_count{prometheus=~\"^$dc$\"},namespace)"
    }
   },
   { "name": "ts", "label": "Time Range", "query": "12h,1d,7d,14d,30d,90d" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow Controller Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(argo_workflows_controller_build_info{prometheus=~\"^$dc$\",namespace=~\"$ns\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Workflows by Phase in the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (increase(argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[$ts]))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Count of Workflows by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow Status  ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase!~\"(Error|Failed)\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase!~\"(Error|Failed)\"})[1m:1m] offset 1h)\nor\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase!~\"(Error|Failed)\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase!~\"(Error|Failed)\"})[1m:1m] offset 1h)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Errors/Failures ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"(Error|Failed)\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"(Error|Failed)\"})[1m:1m] offset 1h)\nor\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"(Error|Failed)\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace, phase) (argo_workflows_total_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"(Error|Failed)\"})[1m:1m] offset 1h)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Controler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow operation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{prometheus=~\"^$dc$\",namespace=~\"^$ns$\"}[5m])) by (le,prometheus,namespace)) ",
     "legendFormat": "{{prometheus}} : {{namespace}} : 95th "
    }
   ]
  },
  {
   "title": "Workflow queue adds ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (increase(argo_workflows_queue_adds_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[2m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (argo_workflows_queue_depth_gauge{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum by (prometheus, namespace, queue_name) (rate(argo_workflows_queue_latency_sum{prometheus=\"prometheus/runner-prometheus\"}[1m]))\n/\n  sum by (prometheus, namespace, queue_name) (rate(argo_workflows_queue_latency_count{prometheus=\"prometheus/runner-prometheus\"}[1m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, level) (rate(argo_workflows_log_messages{namespace=~\"$ns\",prometheus=~\"^$dc$\"}[1m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{level}}"
    }
   ]
  },
  { "title": "WorkflowTemplates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "WorkflowTemplates Succeeded over the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=\"Succeeded\"}[$ts])))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "WorkflowTemplates Failed/Errored over the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"Failed|Error\"}[$ts])))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "WorkflowTemplates Status  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(sum by (prometheus, namespace, phase, name) (argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)\nor\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_workflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{name}} : {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Template Runtime (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(argo_workflows_workflowtemplate_runtime_bucket{prometheus=~\"^$dc$\",namespace=~\"^$ns$\"}[5m])) by (le,name,prometheus,namespace)) ",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{name}} : 95th "
    }
   ]
  },
  { "title": "ClusterWorkflowTemplates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "ClusterWorkflowTemplates Succeeded over the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=\"Succeeded\"}[$ts])))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ClusterWorkflowTemplates Failed/Errored over the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\",phase=~\"Failed|Error\"}[$ts])))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ClusterWorkflowTemplates Status  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)\nor\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace, phase, name) (argo_workflows_clusterworkflowtemplate_triggered_total{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{name}} : {{phase}}"
    }
   ]
  },
  { "title": "CronWorkflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "CronWorkflows Triggered over the last $ts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (increase(argo_workflows_cronworkflows_triggered{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[$ts])))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Workflow Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Workflow Pods by State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, phase) (argo_workflows_pods_gauge{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{phase}}"
    },
    {
     "expr": "increase(sum by (prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 unless\nincrease(sum by (prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)\nor\nincrease(sum by (prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m]) > 0 -\nincrease(sum by (prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[1m:1m] offset 1d)",
     "legendFormat": "{{prometheus}} : {{namespace}} : Pending"
    }
   ]
  },
  {
   "title": "Top 5 Pending Pods by reason in the last $ts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, (increase(sum by (reason, prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[$ts:1m]) > 0)) unless\ntopk (5, (increase(sum by (reason, prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[$ts:1m] offset 1d)))\nor\ntopk (5, (increase(sum by (reason, prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[$ts:1m]) > 0)) -\ntopk (5, (increase(sum by (reason, prometheus, namespace) (argo_workflows_pod_pending_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})[$ts:1m] offset 1d)))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{reason}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "options": {
    "content": "---\n\n[![Pipekit Logo](https://helm.pipekit.io/assets/pipekit-logo.png)](https://pipekit.io?utm_campaign=grafana-dashboard)\n\nPipekit is the control plane for Argo Workflows. Platform teams use Pipekit to manage data & CI pipelines at scale, while giving developers self-serve access to Argo. Pipekit's unified logging view, enterprise-grade RBAC, and multi-cluster management capabilities lower maintenance costs for platform teams while delivering a superior devex for Argo users.\n\nFor help with Argo Workflows metrics, and overall Argo support, contact the Pipekit team at [hello@pipekit.io](mailto:hello@pipekit.io)."
   }
  }
 ]
}