/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodsNamespacePodNameRouteImport } from './routes/pods.$namespace.$podName'
import { ServerRoute as TrpcServerRouteImport } from './routes/trpc'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsNamespacePodNameRoute = PodsNamespacePodNameRouteImport.update({
  id: '/pods/$namespace/$podName',
  path: '/pods/$namespace/$podName',
  getParentRoute: () => rootRouteImport,
} as any)
const TrpcServerRoute = TrpcServerRouteImport.update({
  id: '/trpc',
  path: '/trpc',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pods/$namespace/$podName': typeof PodsNamespacePodNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pods/$namespace/$podName': typeof PodsNamespacePodNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pods/$namespace/$podName': typeof PodsNamespacePodNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pods/$namespace/$podName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pods/$namespace/$podName'
  id: '__root__' | '/' | '/pods/$namespace/$podName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodsNamespacePodNameRoute: typeof PodsNamespacePodNameRoute
}
export interface FileServerRoutesByFullPath {
  '/trpc': typeof TrpcServerRoute
}
export interface FileServerRoutesByTo {
  '/trpc': typeof TrpcServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/trpc': typeof TrpcServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/trpc'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/trpc'
  id: '__root__' | '/trpc'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  TrpcServerRoute: typeof TrpcServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods/$namespace/$podName': {
      id: '/pods/$namespace/$podName'
      path: '/pods/$namespace/$podName'
      fullPath: '/pods/$namespace/$podName'
      preLoaderRoute: typeof PodsNamespacePodNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/trpc': {
      id: '/trpc'
      path: '/trpc'
      fullPath: '/trpc'
      preLoaderRoute: typeof TrpcServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodsNamespacePodNameRoute: PodsNamespacePodNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  TrpcServerRoute: TrpcServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
