/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PodsPodNameImport } from './routes/pods.$podName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PodsPodNameRoute = PodsPodNameImport.update({
  id: '/pods/$podName',
  path: '/pods/$podName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pods/$podName': {
      id: '/pods/$podName'
      path: '/pods/$podName'
      fullPath: '/pods/$podName'
      preLoaderRoute: typeof PodsPodNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pods/$podName': typeof PodsPodNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pods/$podName': typeof PodsPodNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pods/$podName': typeof PodsPodNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pods/$podName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pods/$podName'
  id: '__root__' | '/' | '/pods/$podName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodsPodNameRoute: typeof PodsPodNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodsPodNameRoute: PodsPodNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pods/$podName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pods/$podName": {
      "filePath": "pods.$podName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
