FROM node:lts-slim AS deps
WORKDIR /app

RUN npm install -g pnpm
COPY package.json ./
COPY .npmrc ./
RUN pnpm install

FROM node:lts-slim AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm run build:workflow

FROM node:lts-slim
WORKDIR /app
RUN npm install -g pnpm && pnpm install esbuild-loader
COPY --from=builder /app .

CMD ["pnpm", "run", "start:worker"]
