FROM oven/bun:latest AS deps
WORKDIR /app

COPY package.json bun.lockb .npmrc ./
RUN bun install

FROM node:lts-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build:workflow

FROM node:lts-slim AS runner
WORKDIR /app
RUN npm install esbuild-loader
COPY --from=builder /app .

CMD ["npm", "run", "start:worker"]
